/**
 * Police lineups
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Response } from './response';

export interface AuthResponse extends Response { 
    userId?: number;
    isAdmin?: boolean;
    userFullName?: string;
    authToken?: string;
    tokenExpirationDatetime?: Date;
}