# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BlobsBlobNameBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, blob: str=None):  # noqa: E501
        """BlobsBlobNameBody - a model defined in Swagger

        :param blob: The blob of this BlobsBlobNameBody.  # noqa: E501
        :type blob: str
        """
        self.swagger_types = {
            'blob': str
        }

        self.attribute_map = {
            'blob': 'blob'
        }
        self._blob = blob

    @classmethod
    def from_dict(cls, dikt) -> 'BlobsBlobNameBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The blobs_blob_name_body of this BlobsBlobNameBody.  # noqa: E501
        :rtype: BlobsBlobNameBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def blob(self) -> str:
        """Gets the blob of this BlobsBlobNameBody.


        :return: The blob of this BlobsBlobNameBody.
        :rtype: str
        """
        return self._blob

    @blob.setter
    def blob(self, blob: str):
        """Sets the blob of this BlobsBlobNameBody.


        :param blob: The blob of this BlobsBlobNameBody.
        :type blob: str
        """

        self._blob = blob
