# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LineupOverview(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, lineup_id: int=None, name: str=None, last_edit_date_time: datetime=None, owner_username: str=None):  # noqa: E501
        """LineupOverview - a model defined in Swagger

        :param lineup_id: The lineup_id of this LineupOverview.  # noqa: E501
        :type lineup_id: int
        :param name: The name of this LineupOverview.  # noqa: E501
        :type name: str
        :param last_edit_date_time: The last_edit_date_time of this LineupOverview.  # noqa: E501
        :type last_edit_date_time: datetime
        :param owner_username: The owner_username of this LineupOverview.  # noqa: E501
        :type owner_username: str
        """
        self.swagger_types = {
            'lineup_id': int,
            'name': str,
            'last_edit_date_time': datetime,
            'owner_username': str
        }

        self.attribute_map = {
            'lineup_id': 'lineupId',
            'name': 'name',
            'last_edit_date_time': 'lastEditDateTime',
            'owner_username': 'ownerUsername'
        }
        self._lineup_id = lineup_id
        self._name = name
        self._last_edit_date_time = last_edit_date_time
        self._owner_username = owner_username

    @classmethod
    def from_dict(cls, dikt) -> 'LineupOverview':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LineupOverview of this LineupOverview.  # noqa: E501
        :rtype: LineupOverview
        """
        return util.deserialize_model(dikt, cls)

    @property
    def lineup_id(self) -> int:
        """Gets the lineup_id of this LineupOverview.


        :return: The lineup_id of this LineupOverview.
        :rtype: int
        """
        return self._lineup_id

    @lineup_id.setter
    def lineup_id(self, lineup_id: int):
        """Sets the lineup_id of this LineupOverview.


        :param lineup_id: The lineup_id of this LineupOverview.
        :type lineup_id: int
        """

        self._lineup_id = lineup_id

    @property
    def name(self) -> str:
        """Gets the name of this LineupOverview.


        :return: The name of this LineupOverview.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this LineupOverview.


        :param name: The name of this LineupOverview.
        :type name: str
        """

        self._name = name

    @property
    def last_edit_date_time(self) -> datetime:
        """Gets the last_edit_date_time of this LineupOverview.


        :return: The last_edit_date_time of this LineupOverview.
        :rtype: datetime
        """
        return self._last_edit_date_time

    @last_edit_date_time.setter
    def last_edit_date_time(self, last_edit_date_time: datetime):
        """Sets the last_edit_date_time of this LineupOverview.


        :param last_edit_date_time: The last_edit_date_time of this LineupOverview.
        :type last_edit_date_time: datetime
        """

        self._last_edit_date_time = last_edit_date_time

    @property
    def owner_username(self) -> str:
        """Gets the owner_username of this LineupOverview.


        :return: The owner_username of this LineupOverview.
        :rtype: str
        """
        return self._owner_username

    @owner_username.setter
    def owner_username(self, owner_username: str):
        """Sets the owner_username of this LineupOverview.


        :param owner_username: The owner_username of this LineupOverview.
        :type owner_username: str
        """

        self._owner_username = owner_username
