version: "3.9"
name: police-lineups-db

services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    profiles:
      - debug
      - release
    restart: unless-stopped
    ports:
      - ${POLICE_LINEUPS_DB_PORT}:5432
    environment:
      - POSTGRES_USER=${POLICE_LINEUPS_DB_USER}
      - POSTGRES_PASSWORD=${POLICE_LINEUPS_DB_PASSWORD}
      - POSTGRES_DB=${POLICE_LINEUPS_DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgweb:
    container_name: pgweb
    image: sosedoff/pgweb
    depends_on:
      - postgres
    profiles:
      - debug
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=postgres://${POLICE_LINEUPS_DB_USER}:${POLICE_LINEUPS_DB_PASSWORD}@postgres:5432/${POLICE_LINEUPS_DB_NAME}?sslmode=disable

networks:
  default:
    name: police-lineups-network

volumes:
  postgres-data:
