openapi: 3.0.3
info:
  title: Police lineups
  version: "0.1"
servers:
- url: /
security:
- JwtAuthUser: []
paths:
  /authorization:
    post:
      summary: Logins registered userUser
      operationId: login
      requestBody:
        description: AuthRequest
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
        required: true
      responses:
        "200":
          description: login result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
      security: []
      x-openapi-router-controller: police_lineups.controllers.auth
    patch:
      summary: Renews auth token
      operationId: renew_auth_token
      responses:
        "200":
          description: token renewal result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthTokenRenewalResponse'
      x-openapi-router-controller: police_lineups.controllers.auth
  /users:
    get:
      summary: Returns all users
      operationId: get_users
      responses:
        "200":
          description: a JSON array of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
                x-content-type: application/json
      security:
      - JwtAuthAdmin: []
      x-openapi-router-controller: police_lineups.controllers.users
    post:
      summary: Adds a user
      operationId: add_user
      requestBody:
        description: a user to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserWithPassword'
        required: true
      responses:
        "200":
          description: addition result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
      security:
      - JwtAuthAdmin: []
      x-openapi-router-controller: police_lineups.controllers.users
  /users/current:
    get:
      summary: Returns a user
      operationId: get_current_user
      responses:
        "200":
          description: a JSON object describing the User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      x-openapi-router-controller: police_lineups.controllers.users
    delete:
      summary: Removes a user
      operationId: remove_current_user
      responses:
        "200":
          description: removal result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
      x-openapi-router-controller: police_lineups.controllers.users
    patch:
      summary: Updates a user
      operationId: update_current_user
      requestBody:
        description: update of user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserWithPassword'
        required: true
      responses:
        "200":
          description: update result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
      x-openapi-router-controller: police_lineups.controllers.users
  /users/{user_id}:
    get:
      summary: Returns a user
      operationId: get_user
      parameters:
      - name: user_id
        in: path
        description: id of a user
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: a JSON object describing the User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "404":
          description: user not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptyResponse'
      security:
      - JwtAuthAdmin: []
      x-openapi-router-controller: police_lineups.controllers.users
    delete:
      summary: Removes a user
      operationId: remove_user
      parameters:
      - name: user_id
        in: path
        description: id of a user
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: removal result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
      security:
      - JwtAuthAdmin: []
      x-openapi-router-controller: police_lineups.controllers.users
    patch:
      summary: Updates a user
      operationId: update_user
      parameters:
      - name: user_id
        in: path
        description: id of a user
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        description: update of user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserWithPassword'
        required: true
      responses:
        "200":
          description: update result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
      security:
      - JwtAuthAdmin: []
      x-openapi-router-controller: police_lineups.controllers.users
  /validation/users:
    post:
      summary: Validated properties of a new user
      operationId: validate_new_user
      requestBody:
        description: a user to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserWithPassword'
        required: true
      responses:
        "200":
          description: addition result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
      x-openapi-router-controller: police_lineups.controllers.users
  /people:
    get:
      summary: Returns a list of people
      operationId: get_people
      responses:
        "200":
          description: a JSON array of people
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
                x-content-type: application/json
      x-openapi-router-controller: police_lineups.controllers.people
    post:
      summary: Adds a person
      operationId: add_person
      requestBody:
        description: a person to add
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/people_body'
        required: true
      responses:
        "200":
          description: addition result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
      x-openapi-router-controller: police_lineups.controllers.people
  /blobs/{blob_name}:
    get:
      summary: Serves a blob
      operationId: get_blob
      parameters:
      - name: blob_name
        in: path
        description: name of a blob to serve
        required: true
        style: simple
        explode: false
        schema:
          minLength: 1
          type: string
      responses:
        "200":
          description: a blob
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
                x-content-type: application/octet-stream
        "404":
          description: blob not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptyResponse'
      x-openapi-router-controller: police_lineups.controllers.blobs
  /people/{person_id}:
    get:
      summary: Returns a person
      operationId: get_person
      parameters:
      - name: person_id
        in: path
        description: id of a person
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: found person
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        "404":
          description: person not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptyResponse'
      x-openapi-router-controller: police_lineups.controllers.people
    delete:
      summary: Removes a person
      operationId: remove_person
      parameters:
      - name: person_id
        in: path
        description: id of a person
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: removal result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
      x-openapi-router-controller: police_lineups.controllers.people
    patch:
      summary: Updates a person
      operationId: update_person
      parameters:
      - name: person_id
        in: path
        description: id of a person
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        description: a person to update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
        required: true
      responses:
        "200":
          description: update result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
      x-openapi-router-controller: police_lineups.controllers.people
components:
  schemas:
    AuthRequest:
      required:
      - password
      - username
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    EmptyResponse:
      type: object
      nullable: true
    Response:
      type: object
      properties:
        error:
          type: string
          nullable: true
      example:
        error: error
    AuthTokenRenewalResponse:
      allOf:
      - $ref: '#/components/schemas/Response'
      - type: object
        properties:
          authToken:
            type: string
          tokenExpirationDatetime:
            type: string
            format: date-time
            nullable: true
    AuthResponse:
      allOf:
      - $ref: '#/components/schemas/Response'
      - $ref: '#/components/schemas/AuthTokenRenewalResponse'
      - $ref: '#/components/schemas/User'
    User:
      type: object
      properties:
        userId:
          minimum: 1
          type: integer
          format: int64
        username:
          minLength: 1
          type: string
        isAdmin:
          type: boolean
        email:
          type: string
          format: email
        fullName:
          minLength: 1
          type: string
      example:
        fullName: fullName
        isAdmin: true
        userId: 1
        email: ""
        username: username
    UserWithPassword:
      allOf:
      - $ref: '#/components/schemas/User'
      - type: object
        properties:
          password:
            maxLength: 16
            minLength: 4
            type: string
    Person:
      type: object
      properties:
        personId:
          minimum: 1
          type: integer
          format: int64
        photoBlobName:
          minLength: 1
          type: string
        fullName:
          minLength: 1
          type: string
        birthDate:
          type: string
          format: date-time
        nationality:
          minLength: 1
          type: string
      example:
        nationality: nationality
        photoBlobName: photoBlobName
        fullName: fullName
        personId: 1
        birthDate: 2000-01-23T04:56:07.000+00:00
    people_body:
      type: object
      properties:
        fullName:
          minLength: 1
          type: string
        birthDate:
          type: string
        nationality:
          minLength: 1
          type: string
        photoFile:
          type: string
          format: binary
  securitySchemes:
    JwtAuthUser:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: swagger_server.controllers.authorization_controller.check_JwtAuthUser
    JwtAuthAdmin:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: swagger_server.controllers.authorization_controller.check_JwtAuthAdmin

