---
swagger: "2.4.4"
info:
  version: "1.0.0"
  title: "Sample API"
host: "localhost:8080"
basePath: "/v1"
schemes:
- "http"
paths:
  /users:
    get:
      summary: "Returns a list of users."
      operationId: "users_get"
      parameters: []
      responses:
        200:
          description: "A JSON array of user names"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  User:
    type: "object"
    properties:
      name:
        type: "string"
