swagger: "2.0"
info:
  title: Sample API
  version: 1.0.0
host: localhost:8080
basePath: /v1
schemes:
  - http
paths:
  /users:
    get:
      summary: Returns a list of users.
      x-swagger-router-controller: controllers.users
      operationId: getUsers
      responses:
        '200':
          description: A JSON array of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: '#/definitions/User'
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      email:
        type: string